### PR TITLE
chore(ci): Update CI steps to build the app

### PR DESCRIPTION
**Pull request by Zaid-maker**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/dockge/blob/master/CONTRIBUTING.md

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

Fixes #(issue)

## Type of change

Please delete any options that are not relevant.

- Other

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas
  (including JSDoc for methods)
- [x] My changes generate no new warnings
- [x] My code needed automated testing. I have added them (this is optional task)

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

### CODE REVIEW

**Comment by Zaid-maker** [comment]
pnpm is fast tho 10s to build the app DAMN!

**Comment by louislam** [comment]
> pnpm is fast tho 10s to build the app DAMN!

If you meant `build:frontend`, it is vite 5.0. It is just released a week ago.

https://vitejs.dev/blog/announcing-vite5

But `pnpm install` is amazing of course.

**Comment by Zaid-maker** [comment]
> > pnpm is fast tho 10s to build the app DAMN!
> 
> If you meant `build:frontend`, it is vite 5.0. It is just released a week ago.
> 
> https://vitejs.dev/blog/announcing-vite5
> 
> But `pnpm install` is amazing of course.

No doubt its amazing! 😄 can we update vite on uptime kuma aswell 👀

**Comment by louislam** [comment]
> > > pnpm is fast tho 10s to build the app DAMN!
> > 
> > 
> > If you meant `build:frontend`, it is vite 5.0. It is just released a week ago.
> > https://vitejs.dev/blog/announcing-vite5
> > But `pnpm install` is amazing of course.
> 
> No doubt its amazing! 😄 can we update vite on uptime kuma aswell 👀

Unfortunately , `npm` is used for update/install for non-Docker users, and pnpm is not using the same lock file.

I don't think it is possible to ask everyone to switch to pnpm and don't want to confuse current non-Docker users, so it is not a good idea to switch to pnpm in the middle.

**Pull request merged**
