### PR TITLE
Translations update from Uptime Kuma Weblate

### PR DESCRIPTION
**Pull request by UptimeKumaBot**
Please go to https://weblate.kuma.pet/projects/dockge/dockge/ if you want to contribute too.🐻

If there is anything not clear on Weblate, feel free to ping me (@louislam) here. I can add some screenshots or explanations on Weblate. 

Current translation status:

Weblate translation status

### CODE REVIEW

**Comment by 401U** [comment]
#180 

it seems to work, need your help to configure the webhook @louislam 

see also https://docs.weblate.org/en/weblate-4.16.4/admin/continuous.html#github-setup

**Comment by louislam** [comment]
> #180
> 
> it seems to work, need your help to configure the webhook @louislam
> 
> see also https://docs.weblate.org/en/weblate-4.16.4/admin/continuous.html#github-setup

Appreciated! Will look into it later. Thanks.

**Comment by 401U** [comment]
also do not forget to edit documents to notify contributors that they can use weblate now😎

**Comment by Zaid-maker** [comment]
Did u setup the weblate fr? Thank u so much

**Comment by Zaid-maker** [comment]
> also do not forget to edit documents to notify contributors that they can use weblate now😎

I will do it!

**Comment by 401U** [comment]
> Did u setup the weblate fr? Thank u so much, name should be DockgeBot

1. Yes, i can see French in the languages.
image

2. I cannot change the bot name, as it is the same bot in UptimeKuma, also it is not under my control

also, for the pr title, I changed it to  `Translations update from Kuma Weblate`, it would take effect on future pr

**Comment by louislam** [comment]
> Did u setup the weblate fr? Thank u so much, name should be DockgeBot

It allows one username only, so I think it is acceptable. The functionality is the most important.
```
      - WEBLATE_GITHUB_USERNAME=UptimeKumaBot
```

**Pull request merged**
