### PR TITLE
Readme reference compose file contents

### PR DESCRIPTION
**Pull request by RyanBalfanz**
Reference the contents of `compose.yaml` directly in the README, for example:

https://github.com/louislam/dockge/blob/2e26178d2d18c1c4ee10227d8d0c3193541b086c/compose.yaml#L1-L23

### CODE REVIEW

**Comment by RyanBalfanz** [comment]
> Thanks, but I want to show.

@louislam: Perhaps it is not clear, but the contents will still be shown/visible in the README on Github. It will be displayed in the same way as my original PR description comment.

Here's an article explaining: https://www.stevemar.net/github-code-in-readme/, and the example repo illustrating the feature: https://github.com/stevemar/code-reference-in-readme.

If you still prefer to manage the same file content in two different places then ok no problem. :)

**Comment by louislam** [comment]
https://github.com/RyanBalfanz/dockge/tree/readme-reference-compose-file-contents

Does it also apply to README.md? I checked your branch, it doesn't seem to be working.

**Comment by RyanBalfanz** [comment]
> https://github.com/RyanBalfanz/dockge/tree/readme-reference-compose-file-contents
> 
> Does it also apply to README.md? I checked your branch, it doesn't seem to be working.

Yes, [creating a permanent link to a code snippet](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-a-permanent-link-to-a-code-snippet) works in the README.md (and other files) within a repository.

It won't work in my branch because it is a different repository and I updated the link to point to yours. I [tried to create a repo agnostic permanent link](https://github.com/louislam/dockge/compare/master...RyanBalfanz:dockge:readme-reference-compose-file-contents) but that does not work in GH. By using that first commit in my branch, you can observe the change in action in my repo by looking at the README.md file from that point in history: https://github.com/louislam/dockge/tree/1942b81f1a5567e9b2e6ebf683e26c772c066dd0#advanced.

**Comment by louislam** [comment]
Thanks. It is good.

**Comment by RyanBalfanz** [comment]
On the compose file, I created a new discussion post over at https://github.com/louislam/dockge/discussions/146.

**Comment by louislam** [comment]
Revert back to original, because people don't notice that it is scrollable and only copy first 11 lines. Also there is no copy button.

image

**Comment by RyanBalfanz** [comment]
> Revert back to original, because people don't notice that it is scrollable and only copy first 11 lines. Also there is no copy button.
> 
> image

@louislam You lost some the fixes from https://github.com/louislam/dockge/pull/116 in this revert.

**Pull request merged**
