### PR TITLE
Added Turkish Language

### PR DESCRIPTION
**Pull request by furkanipek**
Added Turkish Language

### CODE REVIEW

**Comment by Zaid-maker** [comment]
> Added Turkish Language

I think Louis didn't implement Adding Language manually to the app, like we have a web based tool to add translations to app it will auto make PR when new translations available but i Louis didn't document this as well.

**Comment by furkanipek** [comment]
In the beginning I wanted to help, of course in the future if there is something like weblate.kuma.pet I would like to contribute to the translation.

**Comment by Zaid-maker** [comment]
> In the beginning I wanted to help, of course in the future if there is something like weblate.kuma.pet I would like to contribute to the translation.

Sure! You are welcome to Help 😄

**Comment by Zaid-maker** [comment]
@louislam what's your taught's on this?

**Comment by louislam** [comment]
Language PR is accepted, since I don't have time to setup Weblate.

**Pull request merged**
