### PR TITLE
Multiple Dockge instances

### PR DESCRIPTION
**Pull request by louislam**
Similar to Portainer agent approach.

A Dockge can connect to other Dockge instances.

### CODE REVIEW

**Comment by almereyda** [comment]
Nice one.

Coolify does this, too.

**Comment by louislam** [comment]
Almost finish! I am quite happy with the agent appoarch so far.

image

**Comment by arpanghosh8453** [comment]
@louislam This is an awesome product! Love it! I love this feature, too. 

Do you think it will be difficult to add filter options based on agents? That will be helpful if the same docker instances are running on multiple hosts. for example, I want to see only docker containers from a specific host/dockage agent ( i.e., current ). You really design nice UI, so I will leave the implementation to you ( if you are interested in this feature ). My suggestion is maybe a check box in the dockge agent section. or maybe a click on a flair to filter?

**Comment by blibdoolpoolp** [comment]
I had a question regarding this, can you only connect in a one-direction fashion? Like I connected very simply from a newly created 2nd Dochge instance on another machine to my first, but then I log into my first one, and I try to connect IT to the SECOND one, and it times out. Is this normal? Am I supposed to just have one cental one and have it connect to all the others? Or am I just missing something?

**Pull request merged**
