### PR TITLE
💡 Feature : add Expand button for wide terminal and compose editor panels

### PR DESCRIPTION
**Pull request by pyxl-dev**
⚠️⚠️⚠️ Since we do not accept all types of pull requests and do not want to waste your time. Please be sure that you have read pull request rules:
https://github.com/louislam/dockge/blob/master/CONTRIBUTING.md

Tick the checkbox if you understand [x]: 
- [x] I have read and understand the pull request rules.

# Description

This PR enhances the terminal expansion functionality across the application. The main changes include:

1. Added a wide terminal modal view in `Terminal.vue` component with improved UI/UX
2. Implemented an expand button in `Compose.vue` for better code editing experience
3. Updated socket handling in `socket.ts` to support multiple terminal instances

Fixes #(no specific issue number provided)

## Type of change

- [x] User interface (UI)
- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I ran ESLint and other linters for modified files
- [x] I have performed a self-review of my own code and tested it
- [x] I have commented my code, particularly in hard-to-understand areas (including JSDoc for methods)
- [x] My changes generate no new warnings

## Technical Details

The changes include:

### Terminal Component (`Terminal.vue`)
- Added expandable terminal view with modal overlay
- Implemented responsive terminal sizing
- Added button to toggle wide terminal view
- Improved terminal UI with header controls

### Compose View (`Compose.vue`)
- Added expand functionality for better code editing
- Implemented modal view for expanded editor
- Maintained terminal state during expansion

### Socket Management (`socket.ts`)
- Updated terminal mapping to support multiple instances
- Enhanced socket binding for expanded terminal views
- Improved terminal event handling

These changes improve the overall user experience by providing more flexible and usable terminal and code editing interfaces while maintaining stability and performance.

## Screenshots (if any)

Please do not use any external image service. Instead, just paste in or drag and drop the image here, and it will be uploaded automatically.

https://github.com/user-attachments/assets/aad29703-a123-4b66-bfe0-bd11714f046a

### CODE REVIEW

**Comment by YoanAncelly** [comment]
Currently working on my own version of dockge

**Comment by mdeeter** [comment]
@YoanAncelly what's the image to use for your version?

**Comment by YoanAncelly** [comment]
@mdeeter It's yoanancelly/dockge:beta atm

Soon i'll put the expand on yoanancelly/dockge:latest

It's on DockerHub

**Comment by pyxl-dev** [comment]
I'm not coding actively anymore so maybe that's why

**Pull request closed without merging**
