### PR TITLE
Updated Arabic translation

### PR DESCRIPTION
**Pull request by abosaad11**
Updated the new strings that needed to be translated.

I don't understand how this website is supposed to integrate with Github:

https://weblate.kuma.pet/projects/dockge/dockge/ar/

So I did both. Completed the translation there and then manually edited `frontend/src/lang/ar.json`.

### CODE REVIEW

**Review by Zaid-maker — COMMENTED** [review]
You don't have to open pull request to translate the web based tool is automatic u just have to translate there and the bot will auto make PR, see #184.

looks like Arabic is 100% translated
image

**Comment by Zaid-maker** [comment]
> You don't have to open pull request to translate the web based tool is automatic u just have to translate there and the bot will auto make PR, see #184.
> 
> looks like [Arabic](https://weblate.kuma.pet/projects/dockge/dockge/ar/) is 100% translated image

**Comment by louislam** [comment]
@abosaad11 Your commit is here:

https://github.com/louislam/dockge/pull/190/commits/c744f3550ee81d129422b558d0f6f044a03e8026



You have done this on Weblate, this pr is not needed.

**Comment by abosaad11** [comment]
@Zaid-maker @louislam 

Thank you both. Excuse my noob question, where do I find the Weblate (bot) commits like the one you linked?

**Comment by Zaid-maker** [comment]
> @Zaid-maker @louislam 
> 
> Thank you both. Excuse my noob question, where do I find the Weblate (bot) commits like the one you linked?

Its basically a pull request opened by Weblate see #150

**Comment by louislam** [comment]
Should be https://github.com/louislam/dockge/pull/190

**Comment by abosaad11** [comment]
Okay thanks I see it here now:
https://github.com/louislam/dockge/pull/190/commits

**Comment by Zaid-maker** [comment]
> Okay thanks I see it here now: https://github.com/louislam/dockge/pull/190/commits

Close this PR

**Pull request closed without merging**
