### PR TITLE
Add ARM github runner and change Node.js version

### PR DESCRIPTION
**Pull request by louislam**

### CODE REVIEW

**Comment by Zaid-maker** [comment]
@louislam ARM64 is your self-hosted runner ?

**Comment by louislam** [comment]
> @louislam ARM64 is your self-hosted runner ?

Yes. 

Unfortunately, the unofficial docker image doesn't provide armv7.

I am too lazy to setup github runner without Docker again.  So it is for arm64 right now.

```yaml
version: "2.3"
services:
  worker:
    image: myoung34/github-runner:latest
    environment:
      REPO_URL: https://github.com/louislam/dockge
      RUNNER_NAME: github-runner-dockge-arm64
      RUNNER_TOKEN: <REDACTED>
      RUNNER_WORKDIR: /tmp/runner/work
      CONFIGURED_ACTIONS_RUNNER_FILES_DIR: /tmp/runner/actions-runner-files
      #     RUNNER_GROUP: my-group
      RUNNER_SCOPE: repo
      LABELS: linux,ARM64
    security_opt:
      # needed on SELinux systems to allow docker container to manage other docker containers
      - label:disable
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/runner:/tmp/runner
      # note: a quirk of docker-in-docker is that this path
      # needs to be the same path on host and inside the container,
      # docker mgmt cmds run outside of docker but expect the paths from within
    restart: unless-stopped
networks: {}

```

**Comment by Zaid-maker** [comment]
> > @louislam ARM64 is your self-hosted runner ?
> 
> Yes.
> 
> Unfortunately, the unofficial docker image doesn't provide armv7.
> 
> I am too lazy to setup github runner without Docker again. So it is for arm64 right now.

Wow I didn't knew we can setup runner using docker sheesh

**Comment by Zaid-maker** [comment]
> > Yes.
> > Unfortunately, the unofficial docker image doesn't provide armv7.
> > I am too lazy to setup github runner without Docker again. So it is for arm64 right now.
> 
> Wow I didn't knew we can setup runner using docker sheesh

**Pull request merged**
